### PR TITLE
fix undefined method accept for refile ~> 0.6

### PR DESCRIPTION
**Pull request by ghost**
Refile 0.6 moves the `Refile::Attacher#accept` method to `Refile::AttachmentDefinition#accept`. I've updated our method call and dependency version, but I imagine we could make our line work for both refile 0.5 and 0.6 by changing the line to:

``` ruby
options[:accept] = attacher.try(:accept) || attacher.definition.accept
```

### CODE REVIEW

**Comment by sindrenm** [comment]
I don't think it's that important for us to support older versions of Refile while we're in a pre-release state anyway, so I'd rather go with your approach right here. Thanks a lot for your PR, @davidjsevans!

**Comment by toothfairy** [comment]
:+1:

**Comment by jgorset** [comment]
:+1:

**Comment by sindrenm** [comment]
Perhaps you wanna give @davidjsevans something, @jgorset?

**Comment by sindrenm** [comment]
Actually. Let me do it. Here's cake, @davidjsevans! :cake:

**Comment by ghost** [comment]
Yay thanks everyone.  This was my first ever open source contribution :grin:  And thanks for the gem too

**Comment by sindrenm** [comment]
That's really cool, @davidjsevans! Welcome to a whole new world. It's a great place to be. :smiley:

**Pull request merged**
